### ISSUE TITLE
Restarted process joining cluster ends up detected as 2 nodes

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#1018]
To recreate
- create a cluster with 2 nodes. Let's call the node 1 and node 2. And let's assum they start with the cool id red and green
- kill node 1 aka red's process.
- red is detected down and removed from the cluster on green
- restart quickwit on the node 1. This time it will get another node id. say blue.

Expected outcome:
- green should see the following cluster members [blue, green]

Actual outcome:
- green sees blue joined, but also detects that red is back. We end up with [blue, green, red]

**Comment by PSeitz** [comment]
The core issue is that the node is sometimes identified via its `node-id` and sometimes via its `SocketAddr`.


Since the member has a new node-id, it is recognized as new member here, but the alive detection only checks `SocketAddr`.
```
for state_change in state_changes {
    let new_member_data = state_change.member();
    let old_member_data = current_members.entry(new_member_data.node_id());
```


Should be straightforward to fix. To avoid further regressions, we should clarify if `SocketAddr` is not enough to identify a node, and use node-id merely as a label for easier debugging.

**Comment by PSeitz** [comment]
This is one analysis of the problem. There are other aspects.

Scenario: 2 Nodes. One stable, one restarts and gets a new node-id.

Issue:
When the node goes down, `state_changes` on the stable node are queued to inform other nodes. This state change includes remote-host and node-id. 
Nodes don't know their own remote-host address. When the node restarts with a new node-id, the stable node will inform it about the node which went down from the `state_changes` array. The restarted node doesn't know this node which went down is itself (different node-id and doesn't know its own remote-host address). When the restarted node queries this node which went down (itself) it will get a response and think this a valid node who joined the cluster. It may notify others about this "new" node.

Possible fix:
When a node requests an Ack from a node, it can also return its node-id as confirmation. The requestor can then validate if for this remote-host is already a node-id registered. The self node can recognize its own id.

Open question:
What if the node is never recognized as down (e.g. very fast restart)

**Comment by fulmicoton** [comment]
@PSeitz Good analysis. That's very clear.
I like the idea to send a node id -if available- **with every message**. We can then ignore any message that is not addressed to ourselves.

> What if the node is never recognized as down (e.g. very fast restart)

I don't understand the question. Upon restart, the node will get a new id. It will never Ack any message with its old id, so the other nodes will eventually identify its own identity as Down, isn't it?

**Comment by PSeitz** [comment]
> I like the idea to send a node id -if available- with every message. We can then ignore any message that is not addressed to ourselves.

Actually I meant the Ack Response, which is used to mark nodes alive again. It will Ack with its node-id.
But extending this to the Heartbeat should make the whole cluster more stable in regards to node-id changes.

I think this will require more changes though. We will need to remove nodes from the memberlist and keep the seed nodes or the member may dangle with the old node-id.

Seed nodes should only be queried if we don't have a member for that host.
So we have two mechanisms:
* Checking seed nodes: Heartbeat -> Ack(node_id). 
This mitigates the queued events issue.
* Checking members: Heartbeat(expected node_id) -> Ack(node_id) or no response id different node_id. 
This mitigates the node never recognized as down issue.


The queued events may still cause some issues, since they may overwrite the new node-id until they are processed.
