### ISSUE TITLE
Gracefully handle failing split search

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#124]
Right now if a single split fails, we fail. We need to at least retry this split, or return partial results and point out the failed split.

**Comment by PSeitz** [comment]
There are multiple sources of errors, some are recoverable:

- Split data is corrupted
- Split data is not corrupted, but data is transferred corrupted (unlikely?)
- The node fails due to not enough ressources
- The node fails due to hardware error
- A bug in tantivy/quickwit

**Comment by PSeitz** [comment]
Retrying on a different node is probably a good idea and having a list of all nodes which failed to serve

**Comment by fulmicoton** [comment]
@Pseitz Absolutely. 
Can  you take over this ticket? It is important to solve it rapidly but we can release without it.

I would add some files are missing. (We can consider this as not recoverable)

**Comment by fulmicoton** [comment]
A simple timeout is also a good reason to retry, but we can handle that later as it is tricker.

**Comment by PSeitz** [comment]
I would start with considering all errors recoverable and then having a list with unrecoverable errors eventually.

**Comment by PSeitz** [comment]
There are different information which could be useful

- Are all requests of one node failing? -> Don't consider this node as alternative of failing requests?
- Is the node ok, but just one the split failing?
- Did all requests fail? (Special case, we don't need to shuffle anything in that case)

After a search we can build 3 groups complete_failure_nodes, partial_failure_nodes (some splits succeeded), no_failure_nodes.

On failure should we still try to hit caches with rendez-vous-hashing or discard it?

In my experience it's also really important to take action to understand the issue when something fails and needs a retry since this can hide otherwise serious bugs.

### Action on repeated failure nodes
Identifying broken nodes should also be important and execute some action like restart or replace and build up some kind of report for analysis. This is also not trivial, because the node could be fine but the split is broken. Maybe we need stats, e.g. when a split fails only on one node. Experiments could also be valuable, like spin up a new node, just to check if it succeeds.

**Comment by fulmicoton** [comment]
> After a search we can build 3 groups complete_failure_nodes, partial_failure_nodes (some splits succeeded), no_failure_nodes.

I wonder if the dichotomy is useful...
- complete_failure_nodes
- partial_or_no_failure_nodes 
Might be sufficient...

If a node fails search one specific split, but succeeded on another one, it sounds like a good signal that
the node is actually healthy. What do you think?

We can also divide the splits into:
- retryable failure: 
- non-retryable failure: file missing
 
> On failure should we still try to hit caches with rendez-vous-hashing or discard it?
You could run rendez vous without the faulty nodes. 


> In my experience it's also really important to take action to understand the issue when something fails and needs a retry since this can hide otherwise serious bugs. (grouping requests with correlation ids is required here)

That sounds wise.

> Action on repeated failure nodes
>Identifying broken nodes should also be important and execute some action like restart or replace and build up some kind of report for analysis. This is also not trivial, because the node could be fine but the split is broken. Maybe we need stats, e.g.  when a split fails only on one node. Experiments could also be valuable, like spin up a new node, just to check if it succeeds.

I agree... However our search being stateless, this isolation process might be a little bit less critical than if it was a traditional shared nothing architecture. I would consider "isolation for forensics" of the broken node more of a nice to have.
Logging the name of the node at first should be sufficient.

**Comment by PSeitz** [comment]
> 
> If a node fails search one specific split, but succeeded on another one, it sounds like a good signal that
> the node is actually healthy. What do you think?

Yes, two groups could be sufficient. But we could have issue regarding to caching, which could lead to requests failing only on combinations of (node, split) with a corrupted cache. I don't know how likely that is. 

> 
> We can also divide the splits into:
> 
>     * retryable failure:
> 
>     * non-retryable failure: file missing
> 

Yes, that's a good idea, but I would start with considering all errors recoverable.

**Comment by PSeitz** [comment]
In the code there are different layers, where errors can occur:

- Inside the node, the search on a split can fail
- The tonic request to the node can fail (all requests to that node fail)
- The future can fail (due to the try_join_all all requests will fail - this should be changed? )

Fails within a node can occur when e.g. split files are missing.

But not sure which categories of errors are in the tonic and future. 
e.g. when a node is not reachable, is it a tonic or future error? 
@mosuka do you know?

**Comment by mosuka** [comment]
@PSeitz I'm not very familiar with it, so I'll look into that too.

**Comment by fmassot** [comment]
My two cents on this issue and your discussion: handling failure and retry on a distributed architecture sounds very hard (I said sounds because I'm definitely not an expert here). I would clearly advance by little steps and do simple things first... That cliché said with so little added value... I hope what follows will be more interesting. 

What you have just merged @PSeitz seems already reasonable because it achieves the following things:
- returning partial results and some information about errors is beneficial from day 1
- target a retry on nodes that don't completely fail

For the next steps, I like splitting the errors into two types, as mentioned by @fulmicoton : 
- retryable failure:
- non-retryable failure: file missing because I think this is the most probable error that can happen to users today

I did not see it here, but I guess we are talking about **1 retry policy**. 

Last but not least, some code has been merged, I did not see new tests, but I saw commented code lines. I know this is a WIP but we need to be extra careful on the code base. A first merge with just the results with failure info + a test would have been totally ok I think.

**Comment by PSeitz** [comment]
> I did not see it here, but I guess we are talking about 1 retry policy.

It could depend on the error, but generally yes. Otherwise we could DDOS ourselves :)

> A first merge with just the results with failure info + a test would have been totally ok I think.

Something like that was the initial plan, but I realized that I need to change from anyhow to thiserror to actually forward the error, there is the split_id context missing there. The aggregation is implemented but the first error not yet, so there is no new functionality that can be tested yet.

**Comment by PSeitz** [comment]
> returning partial results and some information about errors is beneficial from day 1

The partial results are currently internal only. We can return partial results to the caller, but not sure if that is a good idea.

## Retry Node Selection

I had another look and the node selection is more complicated:
Currently there are 2 groups:

- complete failure nodes
- partial failure nodes

But, the set of {complete_failure_nodes, partial_failure_nodes} is not the list of all nodes, only the tried nodes for that search.
The logic is to use only partial failure node if there are partial failure nodes otherwise use only complete failure nodes.

E.g. if we have a use case that has 2 nodes A_SUCCESS and B_ALWAYS_FAIL and a search on split1 selects B_BOO_ALWAYS_FAIL and fails, our sets will look like this:


complete_failure_nodes = {B_ALWAYS_FAIL}
partial_failure_nodes = {}

One approach could be to exclude complete_failure from all nodes, instead of whitelisting from the tried nodes. Although there may be no nodes left, when all are excluded.

## When to Enable Retry
Retry mechanism works well for low failure rate scenarios, after a certain percentage of failures it will be bad for the cluster health, e.g.:
- The few remaining nodes now get a higher load than they can handle
- Hitting nodes with no caches could lead to additional stress on the system.


**So the activation of retry should be coupled to some cluster health metrics.**

**Comment by fulmicoton** [comment]
@PSeitz can we close this ticket?

**Comment by PSeitz** [comment]
Yes, but there are follow-ups:

- There is no doc-store retry. When a node becomes unreachable between search and document retrieval. (It's probably niche in comparison to search failing)

- Have a mechanism to disable retry
