### ISSUE TITLE
Dockerfile and Github action to build and publish release binary files

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#168]

**Comment by evanxg852000** [comment]
@fulmicoton I don't understand the `Dockerfile` part. is this docker file for building the binary?
Gihub hosted action runner can build our binary, but it's going to be limited since they don't provide different architecture per OS.
So currently from gihub provided action runner, we can build for: windows, mac-os, ubuntu but for x86_64, other architecture like aarch64, arm etc... are not available. if we want this, we will have to setup our own self-host runners.
So far I am working on making it work at least for the basic that is provided. Then if we agree or find better ways I can proceed with the chosen direction.

**Comment by evanxg852000** [comment]
Currently we have apple and ubuntu binaries uploaded from the CI [see](https://github.com/quickwit-inc/quickwit/releases/tag/v0.1.2). I don't know but building binaries on apple tend to take way longer. This should be fine since we don't release everyday.
So the release workflow I am proposing is to create a tag locally and push. 
When a tag pushed, `publish` workflow will kick in to build the binaries, create a basic `pre-release` on the repository and upload the binaries on to it. we can now fill the `pre-release` infos, notes and other info and make it public.

**Comment by fulmicoton** [comment]
@evanxg852000 Then that's already perfect :).

**Comment by fulmicoton** [comment]
If the build time or cost becomes a problem we can probably do cross compilation.

**Comment by fmassot** [comment]
I merge the PR but I think we can still improve small things:
- the binaries name should contain the version
- tar.gz the binaries or zip on windows

**Comment by fmassot** [comment]
solved by @evanxg852000 ! thanks, we can close then.
