### ISSUE TITLE
Implement `new` CLI command

### ISSUE THREAD

**Issue by guilload** [quickwit-inc/quickwit#2]
## Spec
`quickwit new ...` creates a new index.

### Command synopsis
```sh
quickwit new <index name> 
	--index-path <path> 
	{--timestamp-field <field name> | --no-timestamp-field}
	[--overwrite]
```

### Command options
`--index-path <path>`  (string) Defines where the index is created.
`--timestamp-field <field name>`  (string) Creates a time-series index. 
`--no-timestamp` (boolean) Creates a non time-series index.
`--overwrite` (boolean) Overwrites existing index.

The `timestamp-field` and `no-timestamp-field` options are mutually exclusive.

#### Creating a time-series index
```sh
quickwit new <index name> --index-path <path> --timestamp-field <field name>
quickwit new nginx --index-path s3://quickwit-indexes/nginx --timestamp-field ts
```

#### Creating a non time-series index
```sh
quickwit new <index name> --index-path <path> --no-timestamp-field
quickwit new nginx --index-path s3://quickwit-indexes/nginx --no-timestamp-field
```

Before completing, the subcommand displays an usage example of `quickwit index` for the index that was just created (see #3 for more details about the `index` subcommand).
```sh
guilload@modern14 ~> quickwit new nginx --index-path s3://quickwit-indexes/nginx --timestamp-field ts
Creating new index at s3://quickwit-indexes/nginx...
Done!
You can now [...] using `quickwit index --index-path s3://quickwit-indexes/nginx --input-path <path to file or directory>`
```

### Design
Assignee(s), please describe in a few sentences how you intend to implement and test this feature.

**Comment by guilload** [comment]
I agree with you, in general, the fewer options a user has to pass, the better. On the other hand, we'd really hate for a user to not use a time-series index when this is what they need, so the `--no-timestamp-field` is there to educate the user.

We can revisit this decision later if people complain.

**Comment by evanxg852000** [comment]
W.I.P

To ease things out for a user, I propose a quickwit-cli to
have it's own local storage on user computer file system.
Ideally all `quickwit` related files will be located in the user's home directory
 within a folder called `~/.quickwit`.

proposition for this directory layout could be where each json file encode the necessary info to 
manipulate and index.
```
~/.quickwit-cli
├── common-crowl
│   ├── data
│   └── metastore.json
├── dev-stream
│   ├── data
│   └── metastore.json
└── test-index
    ├── data
    └── metastore.json
```
In the directory tree above, each folder corresponds to a self-contained index with a metastore.json.
The info in this `metastore.json` file should allow the cli tool to build documents and add them to the index.
It should allow user to search an index without having to type the path all the time by just using the index name.
In fact the each top level folder is an index and the name is also the index name.
The `data/` folder will contain the splits downloaded on the local file system. This is proposition as it's not 
clear to me yet if we intend to use the downloaded splits from previous run of the cli tool. 

let's dig further into `metastore.json` to see how we plan this to workout.
```json
{
    "quikwit-cli-version": "0.1",  
    "tantivy-version": "0.14",
    "name": "<index name> used in new command", // just the folder name
    // this is persisted so that user won't have to specify --index-path
    // I think it's just easier to `quickwit search --index=test --query="yes or no"` and let the tool figure out the path/uri
    // this will introduce a `pull` command as in `quickwit pull --path=s3://quickwit-indexes/` see details below
    "path": "<index path> used in new command", 
    "credentials": { 
        // [s3, minio, etc...] credentials
        // the path (protocol) should help the StorageFactory determine which storage instance to spin up
    },
    "timestamp_field": "timestamp",
    "schema": { // this schema helps construct a doc builder on the fly for producing document
        "fields": [
            {
                "name": "name",
                "type": "string",
                "options": ["string"]
            },
            {
                "name": "timestamp",
                "type": "uint64",
                "options": ["fast"] 
            },
            {
                "name": "trace_id",
                "type": "string",
                "options": ["string"]
            },
            {
                "name": "span_id",
                "type": "string",
                "options": ["string"]
            },
            {
                "name": "severity_text",
                "type": "string",
                "options": ["string"]
            },
            {
                "name": "severity_number",
                "type": "uint64",
                "options": ["indexed"]
            },
            {
                "name": "body",
                "type": "string",
                "options": ["stored", "indexed"]
            },
            {
                "name": "facet",
                "type": "facet",
                "options": ["indexed"]
            },
            {
                "name": "structured",
                "type": "bytes",
                "options": ["indexed"]
            },
            {
                "name": "__source",
                "type": "string",
                "options": ["stored"]
            }
        ]
    },
    "splits": [
        // list of searchable splits
        // this list portion should be kept up to date all the time.
        // when the indexer or any other component changes the metastore of this index on s3,
        // it should make sure to update this local version 
        // solution: the simplest could be best, just download and overwrite this metastore 
    ]
}
`

In order to construct a doc builder from the schema, we need a kind of mapping from json value to tantivy
object. Here is my proposed mapping. it's inspired from this (nodejs tantivy binding)[https://github.com/strangerlabs/tantivy]
// following is the mapping of field type to tantivy FieldType
string  -> Str
uint64 -> U64
int64 -> I64
float64 -> F64
date -> Date
facet -> HierarchicalFacet
bytes -> Bytes

// following are the options mappings to tantivy FieldOption<T>
text -> TEXT
string -> STRING
indexed -> INDEXED
stored -> STORED
fast -> FAST


## new command

when a user enters this command: 
```quickwit new <index name> --index-path <path> 
    -- schema <schema json file path>
    {--timestamp-field <field name> | --no-timestamp-field}
    [--overwrite]
```

-we check if the folder `~/quickwit/<index name>` exists. 
if it exist we need to report to the user that "an index with this name <index name> already exist. you could overwrite with the flag"
if the folder does not exist, we go ahead and creates it.
Before creating the index local folder, we need to have a schema. I propose we have our doc builder as default schema.
when user does not provide his own schema file.
in case he does provide, we need to check/validate the schema during index creation. by validate I mean if we can instanciate a doc builder from the 
json present in the schema file. An unusable schema error should be

**Comment by evanxg852000** [comment]
I have noticed that <index path>  is kind of used as the identifier for targeting any operation. If we don't use the index name, I think it's fair to drop it. if we need an internal name, we can generate something new.

**Comment by evanxg852000** [comment]
Implementation ideas:
When a user enter the `new` command.

We first check if the folder at `<index-path>` exists and is not empty.
If so we display an index creation error, because the folder is not empty.
If the folder does not exist or is empty, we create the folder and create the `metastore.json` file 
inside it. We perform the same check if we are dealing with object storage like s3, the only difference is that 
the actual index creation is a serialization of the `metastore.json` file directly into s3.

The new command provides a flag to overwrite an existing index. we need to be careful not deleting a user folder or 
files. when that flag is passed we will check if the existing `<index path>` actually contains a `metastore.json` file
before creating a new one over it. 

I propose the `metastore.json` to have the following content.

```json
{
    "quikwit-cli-version": "0.1",  
    "tantivy-version": "0.14",
    "name": "<index name> specified from the new command", 
    "path": "<index path> specified from the new command",   
    "schema": {
        "timestamp_field": "<timestamp field> specified from the new command or null",
    },
    "splits": [
        "<split_one>": {
            "metadata": "<SplitMetaData>",
            "files": ["<manifest_entry>"],
        },
        "<split_two>": {
            "metadata": "<SplitMetaData>",
            "files": ["<manifest_entry>"],
        }
    ]
}
```

The `schema` property could hold a list of fields and their indexing option. For now, it will be used to 
store the `timestamp_field` or null if `--no-timestamp-field` flag is used.
For a newly created index, the splits property will be empty. This will get more entries during indexing and split merge.

Change proposition: 
- I have noticed that `<index name>` is not used in further `quickwit` commands. Could we probably drop it?
Or we could keep the `<index name>` since that one is shorter and find a way to make a direct correspondence between 
`<index name>` and `<index path>`. My proposed solution to this direction is that to have a `~/.quickwit`  folder into the user's
home directory. the layout of this folder would be:
```
~/.quickwit-cli
│
└── store.json
```
The content of this file would be:
```json
{
    "nginx": "~/indexes/ngin-logs",
    "caddy": "s3://quickwit-indexes/caddy_logs",
}
```
This can help user not having to type the path all the time but instead use the index name as the target for all 
quickwit operations. Note that if the user wants to query on another machine he might have to specify the `<index-path>`
since this mapping might be unknown on the new machine. The solution is that all command using `<index-path>` could go ahead store 
an entry in the above `store.json` when they succeed and inform the user they can now use `<index name>` as an alias of `<index-path>`
`quickwit search --index=caddy --query="crash recovery"`

- regarding the doc builder, I propose to use the schema property as above, if the user specify 
fields customization, then we create a doc builder on the fly to ingest the document. otherwise we 
use a generic doc builder as @guilload proposed. The default will always be a generic doc builder
since that's what the current new command will output.
Later we can add a command flag allowing user to specify a their own schema file.

```
quickwit new <index name> --path <index-path> 
    -- schema <schema-json-file-path> [--overwrite]
```

**Comment by guilload** [comment]
> The new command provides a flag to overwrite an existing index. we need to be careful not deleting a user folder or
> files. when that flag is passed we will check if the existing `<index path>` actually contains a `metastore.json` file
> before creating a new one over it.
Yes, we can rely on the implementation of the `delete` command to do so safely.
 
> * I have noticed that `<index name>` is not used in further `quickwit` commands. Could we probably drop it?
Yes, let's remove the `<index_name>` parameter in the CLI and the property `index_name` in the metastore file. Additionally, we also propose that the `index_path` property in the metastore file be removed since the `--index-path` parameter is always required.

> * regarding the doc builder, [...]
@fulmicoton and I want to go a little bit further in separating the concerns between doc builder and schema. So, we propose something along those lines:
```json
"doc_builder": { "name": "opentelemetry", "params": {}}
```
coupled with a `DocBuilderFactory: Fn(name, params) -> DocBuilder`. For the first version of the CLI, we will only support the `dynamic` doc builder. I'm about to open a new issue for the implementation of this new doc builder.

@evanxg852000 @fulmicoton @mosuka, what we are discussing here actually influences #12, let's converge on the same spec for the file implementation of the metastore.

**Comment by guilload** [comment]
I also suggest that we remove the `quikwit-cli-version` and `tantivy-version` properties. They have no bearing on the file format, which will evolve independently. We may want `"version": 0`, however.

**Comment by evanxg852000** [comment]
@guilload I can summarize that we want our `metastore.json` to have the following:
```json
{
    "version": "{$CARGO_PKG_VERSION} of the quickwit-cli",  
    "doc_builder": { 
        "name": "opentelemetry", 
        "params": {}
    },
   "timestamp_field": "<timestamp field> specified from the new command or null",
    "splits": {
        "<split_one>": {
            "metadata": "<SplitMetaData>",
            "files": ["<manifest_entry>"]
        },
        "<split_two>": {
            "metadata": "<SplitMetaData>",
            "files": ["<manifest_entry>"]
        }
    }
}
```
 @fulmicoton @mosuka @guilload we still need to agree on what goes on splits. looking at the approach in the Metastore and the command scaffold. Here is a skeleton proposition.

```rust

// A Split identifier (URI or path for disk base split could be used )
pub type SplitId = String;

struct MetastoreInfo {
    pub version: String,
    pub timestamp_field: Option<String>,
    pub doc_builder_info: DocBuilderInfo,
    pub splits: HashMap<SplitId, SplitInfo>,
}

// DocBuilderInfo embed necessary info that can be used to create a DocBuilder instance
struct DocBuilderInfo {
    // Name used in DocBuilderFactory to create an instance of DocBuilder
    pub name: String,
    //  Parameters used in DocBuilderFactory to create an instance of DocBuilder
    pub params: HashMap<String, String>,
}

// a top level split struct to hold info about split
struct SplitInfo {
    // Identifier for this Split 
    pub split_id: SplitId,
    // State of the split [Staged, Published, ScheduledForDeleted]
    pub status: SplitState,
    // The split manifest
    pub manifest: SplitManifest,
}

fn create_index(
    index_path: &str,
    timestamp_field: Option<&str>,
    overwrite: bool,
) -> anyhow::Result<()> {
    // delete if already exist & overwrite
    if overwrite {
       let result = delete_index(index_path);
       // if ErrorKind is FileDoesNotExist we can just go ahead and create the index
       // otherwise propagate the error
       if let Err(err) = result {
            err.kind() != DoesNotExist {
                return Err(err);
            }
       }
    }

    // construct an instance of `MetastoreInfo`
    let store_info = MetastoreInfo {
        version: String::from(env!("CARGO_PKG_VERSION")),
        timestamp_field: timestamp_field.map(|filed| filed.to_string()),
        doc_builder_info: DocBuilderInfo {
            name: "opentelemtry".to_string(),
            params: HashMap::new(),
        },
        splits: HashMap::new(),
    };

    // Find out the storage to use
    // TODO: I propose to implement a FileStorage in `storage` crate 
    // also move this logic there for FileStorage to be fallack.
    // but we can keep it simple as well with just tokio::fs
    let mut index_uri = index_path.to_string();
    if !index_uri.contains("://") {
        index_uri.insert_str(0, "file://");
        //create the directory at index_uri (ex. /home/text-index)
    }
    let storage_resolver = StorageUriResolver::default();
    let storage =  storage_resolver.resolve(index_uri)?;

    // serialise store_info into metastore.json using storage
    storage.put("metastore.json", serde_json::to_vec(&store_info)?)?;

    debug!(
        index_path = index_path,
        timestamp_field =? timestamp_field,
        overwrite = overwrite,
        "create-index"
    );
    Ok(())
}
```

**Comment by evanxg852000** [comment]
I am also not sure if you feel this will make things complex having `file://` storage implementation.

**Comment by fulmicoton** [comment]
Let's start simple at least to begin....

Resume is hard because it assumes some kind of Seek operation and it would be nice to have some notion of checkpointing in the index. We do not have either today, so for the moment let's assume we do not handle resume...

Indexing from a storage would require streaming (or download eveyrthing and then work). It might be possible to either add streaming in the API, or emulate streaming through pagination, but this is quite tricky.
Let's start simple! I suggest we only handle as an input:
- stdin
- single file

In order to make our code clean and stay ready for the future (tm), we can have an a `run_index` function that takes a Box<dyn io::Read> for argument

The Box<dyn io::Read> is built from the Cli args.

So `fn index_data(indexargs)`would just create a Box<dyn io::Read> and pass it to a `run_index()` function (in a different file).
The function would then start by wrapping it into a `BufReader`

**Comment by fmassot** [comment]
Closing now as we have a function new command, note that the `--timestamp-field` is no more here for now as it's defined in the doc mapper.
