### ISSUE TITLE
Add a healthcheck endpoint on search server

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#268]
This is useful when you want to host search servers behind a load balancer. The load balancer generally expects an endpoint to check if the server is correctly running.

I think we did that for barrel.

**Comment by fulmicoton** [comment]
I'd love to have an endpoint with the list status of the servers in the cluster too.

**Comment by mosuka** [comment]
Created an issue for the endpoint that lists the status of the servers in the cluster.
https://github.com/quickwit-inc/quickwit/issues/354

**Comment by mosuka** [comment]
@fmassot @fulmicoton 
This is a proposal for a health check REST API definition.

The search API server needs to expose its own health status so that clients can determine if the server is available or not.
There are two types of health checks :
- Liveness check
- Readiness check

### Liveness check

Checks if the process is alive. It assumes, for example, when a process goes down and becomes unresponsive.
This endpoint returns 200 and should be used to check the API server's health.

Endpoint:

```
GET /health/livez
```

Status code:
- 200: Alive

Response body example:

```
{
    "liveness_state": "alive"
}
```


### Readiness check

Checks if the process is in a ready state. For example, it is assumed that the process is alive but cannot return a response due to being in the initialization process or not being able to communicate with the dependent database, etc.
This endpoint returns 200 when the API server is ready to respond to queries.

Endpoint:

```
GET /health/readyz
```

Status code:
- 200: Ready

Response body example:

```
{
    "readiness_status: "ready"
}
```

**Comment by fmassot** [comment]
Thanks @mosuka for digging the subject.

Currently, I see no difference at all between the two endpoints. For the `readyz` endpoint, as you said, we would need to check if we can connect to the metastore for example.

I suggest of keeping for the moment only the alive endpoint and simplify the code (remove `impl HealthService`, `live_predicate`. Really all dead code or code that may be useful later but we don't know when should be deleted.

**Comment by mosuka** [comment]
Ok, I'll remove the unnesessary code. Thanks.
