### ISSUE TITLE
Make the throughput gauge in the indexing cli smarter

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#284]
Right now the throughput displayed is the overall average throughput since the start of the program.

We would like an average over a short window in order to be able to observe the possible fluctuation.

**Comment by fulmicoton** [comment]
(a fun small ticket to rest from the release :) )

**Comment by evanxg852000** [comment]
@fulmicoton So choosing let's say a window of 5s.
- I guess the first 5s can be calculated just like we currently do since from 0s to 5s we cannot say it's zero.
- There is also this enhancement that's needed at the end, when all the docs are processed and the last split is being uploaded, the number of byte processed no longer increases causing the throughput to start dropping. we can maintain this but I propose we stop calculating and just use the calculated value from that point.
