### ISSUE TITLE
Implement `index` CLI subcommand

### ISSUE THREAD

**Issue by guilload** [quickwit-inc/quickwit#3]
## Description
Indexes a Newline Delimited JSON (NDJSON) dataset located at `input-path` or read from *stdin*. The data is appended to the target index specified by `index-path` unless `overwrite` is passed. `input-path` can be a file or a directory. In the latter case, the directory is traversed recursively. Local and remote datasets (S3) are supported. By default, the process uses 4 threads and 1GiB of memory per thread. The `num-threads` and `heap-size` options allow for customizing those settings.

## Synopsis
```sh
quickwit index
	--index-path <path> 
	[--input-path <path>]
	[--num-thread <num threads>]
	[--heap-size <num bytes>]
        [--overwrite]
```

## Options
`--index-path` (string) Specifies the location of the target index.
`--input-path` (string) Specifies the location of the NDJSON-formatted source dataset.
`--num-thread` (integer) Number of allocated threads.
`--heap-size` (integer) Amount of allocated memory.
`--overwrite` (boolean) Overwrites existing data.

## Examples
*Indexing a local dataset*
`quickwit index --index-path s3://quickwit-indexes/nginx --input-path nginx.json`

*Indexing a remote dataset*
`quickwit index --index-path s3://quickwit-indexes/nginx --input-path s3://quickwit-datasets/nginx.json`

*Indexing a dataset from stdin*
`cat nginx.json | quickwit index --index-path s3://quickwit-indexes/nginx`
`quickwit index --index-path s3://quickwit-indexes/nginx < nginx.json`

*Reindexing a dataset*
`quickwit index --index-path s3://quickwit-indexes/nginx --input-path nginx.json --overwrite`

*Customizing the resources allocated to the process*
`quickwit index --index-path s3://quickwit-indexes/nginx --input-path nginx.json --num-threads 8 --heap-size 16GiB`

## Output
Before completing, the command displays a usage example of `quickwit search` for the target index (see #4 for more details about the `search` command).
```sh
guilload@modern14 ~> quickwit index --index-path s3://quickwit-indexes/nginx < nginx.json
Indexed 12345 docs in 3s.
You can now query your index with `quickwit search --index-path s3://quickwit-indexes/nginx --query "barack obama"`
```

## Design and implementation pointers
The command creates and uploads splits to `index-path` and updates the meta store file. When appending data, merging newly generated splits with "older" splits is out of scope for this iteration. However, the command should create a new split every 5 million documents. The command should also be able to generate and upload two splits concurrently. We want a Quickwit split to be comprised of a single Tantivy segment, so we should wait for Tantivy to merge all the segments before uploading a split. The command should be recoverable, i.e. we should be able to hit Ctrl+C to interrupt the process and then resume right where we left off. Tantivy has a mechanism to embed metadata within a commit, which should help to implement this behavior. Finally, the command should display some statistics (number of docs indexed, throughput, ...) as the indexing progresses.

Assignee(s), please complete this paragraph further as you're going through the implementation.

## Testing
Assignee(s), please describe in a few sentences how you intend to test this command.

**Comment by evanxg852000** [comment]
Let's break this down

### Delete splits if `override`
if the user specifies `override` flag, we first need to delete the existing splits in the index at `index-path`


###  Uniformly retrieved docs from the following sources (Single File, Directory, S3, StdIn)
We will implement this with an `Iterator` interface. This will allow jumping to a specific  line to retrieve a document and send for indexing. To avoid unnecessary io work, we will wrap the Iterator interface into a new Trait called `DocumentReader`.
```rust
pub trait DocumentReader {
    fn next_line(&mut self) -> Option<String>;
    // Overriden because we want to avoid io operations
    // when performing Iterator::skip(n) 
    // `Storage::get_slice(..)` supports random access
    fn nth_line(&mut self, n: usize) -> Option<String>;
}
```

Then we will have a `DocumentRetriever` component to that will choose the appropriate `DocumentReader` 
based on the `input-path`

```rust
pub struct DocumentRetriever<T: DocumentReader> {
    reader: T,
}

impl<T: DocumentReader> Iterator for DocumentRetriever<T> {
    type Item = String;

    fn next(&mut self) -> Option<Self::Item> {
        self.reader.next_line()
    }

    fn nth(&mut self, n: usize) -> Option<Self::Item> {
        self.reader.nth_line(n)
    }
}

/// A reader that goes to s3 to read one newline delimited json file
pub struct S3Reader {}

/// A Reader that reads newline delimited json file from StdIn 
pub struct StdInReader {}

/// A Reader that reads one newline delimited json file from file system 
pub struct SingleFileReader {}

/// A Reader that recursively reads all newline delimited json file from a file system directory.
/// 
/// In order to provide a consistent view for Iterator::skip(n) 
/// we need to traverse and lexicographical sort the collected list of files first
pub struct DirectoryFileReader {}
```

In the preceding snippet, all concrete readers will implement the `DocumentReader` trait.

###  Create a DocBuilder from the index metastore.json
We should be able to obtain the doc_builder property from the metastore and instantiate a docBuilder from it.

## Design indexer to support concurrent split upload
The indexer will be implemented in a component called `DocumentIndexer`.
It will receive document from `DocumentRetriever`  via a tokio mpsc channel.
The documents received in the `DocumentIndexer` will be added to an internal `tantivy::IndexWriter`
up to a certain threshold (5M docs / split). Once the threshold is reached, we instruct the Metatsore to 
render this split. Render the split means:
 - Merging all segments into one using `tantivy::IndexWriter::merge(segment_ids)`. 
 - Stage, upload and publish the split using the metastore
 - possibly retry when it fails. It would be a shame to have to re-index 5M docs without trying our best.

To support concurrent split upload, as soon as a split is completed (has reached the number of docs).
all subsequent actions on the split will be performed into another thread/task. This will allow the `DocumentIndexer`
to keep accepting documents from  `DocumentRetriever` to build the subsequent splits. 

**Note**: We could be more efficient by having multiple `DocumentIndexer` working concurrently. But we have this requirement of being able to resume indexing from where we left off. To support that efficiently, we need to keep for each split, a commit metadata denoting the sequential number of the first and last document in the `input-path` for each split.
```json
"split_test": {
    ...
    "start_doc": 12,
    "end_doc": 40
}
```
This format allows us to know what part of the `input-path` were actually indexed and published by the meatstore.
Keeping the split construction sequential in regard to the `input-path` is key to being able to jump around and select a portion
of the `input-path` to re-index after CTRL+C.

### Setup indexer taking into account num_threads and heap_size
The `tantivy::IndexWriter` used by the `DocumentIndexer` should be configure to use these settings.

###  Capturing Statistics 
Once the indexing starts, we keep a counter for elapse time, and the number of document indexed so far. 
The number of document indexed is updated whenever a new split is published and we expect a channel to receive the number of document indexed, the number of document we could not parse. We use those information to calculate the throughput. In order to display them interactively in the terminal, I plan to use [crossterm](https://crates.io/crates/crossterm) crate. 

###  How we intent to test?
I will add unitest where  appropriate. 
I will also need to have an integration test on the command to test different usage (tempdir, s3 etc..).
Of course manually testing it as well with S3.

**Comment by fulmicoton** [comment]
Let's start simple at least to begin....

Resume is hard because it assumes some kind of Seek operation and it would be nice to have some notion of checkpointing in the index. We do not have either today, so for the moment let's assume we do not handle resume...

Indexing from a storage would require streaming (or download eveyrthing and then work). It might be possible to either add streaming in the API, or emulate streaming through pagination, but this is quite tricky.
Let's start simple! I suggest we only handle as an input:

stdin
single file
In order to make our code clean and stay ready for the future (tm), we can have an a run_index function that takes a Box for argument

The Box is built from the Cli args.

So fn index_data(indexargs)would just create a Box and pass it to a run_index() function (in a different file).
The function would then start by wrapping it into a BufReader

**Comment by fulmicoton** [comment]
open question @guilload :
Right now, we tend to upload and publish splits as we create them.

A crash creates a situation where the user cannot cleanup the mess. We might want to make it possible to publish several splits atomically and do that at the very end of the process.

**Comment by guilload** [comment]
Yes, I think that makes sense given that we got rid of the ability to resume where we left off after a crash.

**Comment by evanxg852000** [comment]
@fulmicoton @guilload 
Please regarding publishing the splits at the very end of all indexing & upload;
Do we want to still publish successfully uploaded splits even if some failed to upload or do we want a full or nothing behavior?

**Comment by fulmicoton** [comment]
We want an all or nothing behavior.
We might need to change the metastore API to do that by the way.

Can you open a ticket so that we keep in mind to revisit that?

**Comment by fmassot** [comment]
I'm closing this issue as we have a working implementation.
