### ISSUE TITLE
Escaping of tags and handling the case where there are too many tags

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#437]
We probably should avoid sending all of the tags when there are too many tags in a split.

(discuss your solution/spc in the ticket)

I suggest we add a tag expressing there are too many tag value for this field. Something semantically equivalent to `field:*`
Any filter on the tags should match such a split.

One problem though:
Right now we have nothing to escape our tag token values.

If a tag field contained "*" we could actually end up with a collision.

We probably want to have some kind of escaping when we create the tags.
(detail in the issue which escape scheme we should use.)

**Comment by evanxg852000** [comment]
I would favor the escaping strategy if we plan to have more than one special characters `*` in this tagging mechanism each with its meaning. Then the escaping character I would go for is `\` for escaping all special characters including the `\` itself.
This means these incoming tags will be internally stored as 
```
device:*fbit  -> device:\*fbit
device:foo\fbit  -> device:foo\\fbit
device:foo\*fbit  -> device:foo\\\*fbit
```
Currently, we don't support tag expression for querying, but when we do then we also need to instruct the user to use the same escaping scheme to clarify his intent. we will most likely use `city:*` to query all split with at least one `city` field. Escaping here is inevitable for supporting tag query expressions.

In my opinion, if we are only trying to communicate internally that a special value means too many tags, I would go for `field:__quickwit_too_many__` and avoid the escaping at this stage. so that escaping can only be involved when we support query expression. We can then document that `__quickwit_too_many__` is a special tag value that should be avoided or raise an error for documents using this value.

**Comment by fmassot** [comment]
@evanxg852000 something like 1000 per field sounds a good start. We can use `total_num_tokens` available on the inverted index to know if we should add tags or not.
I'm not fan of `__quickwit_too_many__`. `TOO_MANY_VALUES` ?
