### ISSUE TITLE
Add a CLI command for listing and filtering splits easily

### ISSUE THREAD

**Issue by guilload** [quickwit-inc/quickwit#541]
**Is your feature request related to a problem? Please describe.**
For troubleshooting purposes, I want to list the splits of a given index, optionally filtering them by state, time range, ...

**Describe the solution you'd like**
`quickwit list-splits  -index-id my_index --state staged ...`

**Describe alternatives you've considered**
Today, I can query the metastore directly with the native API, SQL, or manipulating the JSON file (`jq`). I can also do a `ls` on the file system.

**Comment by guilload** [comment]
Bonus point if we have file system only mode that does not hit the metastore. See #376.

**Comment by evanxg852000** [comment]
@guilload In regard to listing the splits, we cannot do that right now with file system only mode for index that reside on s3 and whose metastore resides in PostgreSQL for instance. We probably need to introduce `Storage::list(path) -> Vec<FileEntry>` API.To list the content of a directory on FS or prefix on object storage. 
We can also use the metastore for now.
 WDYT ?

**Comment by guilload** [comment]
Let's just use the metastore for this iteration.

**Comment by evanxg852000** [comment]
@guilload while implementing it, I have made some decisions on which I need your take.
- For now `state` is mandatory since `Metastore::list_splits(..., split_state: SplitState, ...)`, so we can only list for one SplitState. Few weeks ago you mentioned this (it's not intuitive). We can make change the API to accept an array of SplitState, where an empty array would mean `any state`. I think it could be a good time to change the API. right?
- `from` and `to` flags respectively correspond to `split.time_range.start` and `split.time_range.end`, should we introduce flags for `create_timestamp` & `update_timestamp` ?
- Talking about timestamps, these are the format we currently support `2020-10-31` or `2020-10-31T02:00:00`. The former will just be transformed into `2020-10-31T00:00:00`
