### ISSUE TITLE
Define and enforce the restriction on index_id

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#56]
We need to define and enforce what kind of string is accepted as an index-id.

Please edit this ticket to drive the discussion.
Read #55 to understand the actual nature of an index_id.

**Comment by fmassot** [comment]
vespa & ES: ["a"-"z","A"-"Z", "_"]["a"-"z","A"-"Z","0"-"9","_"]*.

- es: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-indexing.html
- vespa: https://docs.vespa.ai/documentation/reference/schema-reference.html#index

**Comment by fulmicoton** [comment]
es accepts unicode or is it ascii only?

**Comment by fmassot** [comment]
good question... and yes they accept unicode : https://discuss.elastic.co/t/index-name-type-name-and-field-name-rules/133039/2
I would stick to ascii as I can only see stupid things coming from accepting unicode, and I don't see any added value in accepting unicode

**Comment by evanxg852000** [comment]
I can see @fmassot  has already put a lot of thought into this. reading both ES vs Vespa, I would prefer the Vespa version for the following reasons:
- ES version seems to not be stable because of the different characters they support
- Vespa version seems to be very simple
- Vespa version is Pretty-URL friendly because of the simplicity which is good for s3 (probably sharing the index URL)

I suggest treating the `_` character as special. That is, an index should not start with `_` even if we don't have use for it at the moment. we may want to treat exceptionally some indices in the future.

**Comment by fmassot** [comment]
yes totally agree with that, and let's start with something restrictive, if people are so angry to not be able to place something like 💩 in the index name then we can reconsider it.
