### ISSUE TITLE
Implement validate method for `IndexConfig`

### ISSUE THREAD

**Issue by guilload** [quickwit-inc/quickwit#757]
We have to enforce some rules. For instance:
- the `demux_field` should be a tag field
- the `timestamp_field` should be a mapped field
- the `default_search_fields` should be mapped fields 
- k * `min_level_num_docs` < `split_max_num_docs`
- ...

**Comment by PSeitz** [comment]
@guilload 
There are already some checks in `DefaultIndexConfigBuilder::build`.

e.g. demux field is automatically added as tag field 
```
info!(
    "Demux field name `{}` is not in index config tags, add it automatically.",
    demux_field_name
 );
```

Should there be additional checks on the trait level? If someone provides a custom `IndexConfig` these checks would be missing, but I don't know if this an actual use case currently, since the `cli` uses `DefaultIndexConfig`

**Comment by guilload** [comment]
Sorry about the confusion here, but I'm talking about `quickwit_config::IndexConfig.` The current `IndexConfig` is going to be renamed `DocMapping` or something like that.

@fmassot might be a better assignee for this ticket since we've already discussed this extensively.

**Comment by fmassot** [comment]
Basic validation is done.
